### ISSUE TITLE
Datasets for labs 4 & 5

### ISSUE THREAD

**Issue by WaltGurley** [ncsu-libraries-data-vis/teaching-datasets#1]
@clairecahoon I went ahead and created clean datasets for labs 4 and 5 (moma_paintings_final.csv and moma_photographs_final.csv). I applied most, but not all, steps from lab 3 and some additional steps. The new columns are (Area (cm^2), Aspect, OilPainting, and YearCreated), and I lowercased all of the Gender data.

Check these out and feel free to edit them as needed with the data-prep notebook

**Comment by clairecahoon** [comment]
Thanks! I'll take a look and see if there are any other steps to add to the data prep.
